### ISSUE TITLE
due_date를 빠른 지정으로 설정 시 무조건 UTC 날짜로 설정됨

### ISSUE THREAD

**Issue by JedBeom** [GooseMoment/Peak#198]
8월 8일 새벽 한 시쯤에 있었던 일입니다...
![Screenshot 2024-08-08 at 12 33 04](https://github.com/user-attachments/assets/501734be-292b-4ce7-b9f5-64c9f0f2e873)

빠른 지정의 "오늘"을 눌렀더니 8월 8일이 아니라 8월 7일로 날짜가 찍혀버렸습니다. 아마 `@components/project/taskDetails/Due.jsx:44`가 문제인 것 같습니다.

```js
due_date = date.toISOString().slice(0, 10)
```

여기서 `toISOString()`을 사용해서, 무조건 UTC기준 날짜가 찍히는 것 같습니다.

**Comment by minyoy** [comment]
PR #268 에서 수정했습니다!
