### ISSUE TITLE
ProjectEdit & DrawerEdit 열리지 않음

### ISSUE THREAD

**Issue by JedBeom** [GooseMoment/Peak#234]
프로젝트나 서랍을 수정하려고 하면 에러 화면이 발생합니다.
프로젝트나 서랍을 생성할 때는 문제가 발생하지 않습니다.
<img width="1512" alt="Screenshot 2024-08-29 at 11 22 23" src="https://github.com/user-attachments/assets/a3b904c0-00ca-43f7-a3fc-cc3b93611381">

`inputRef`와 관련된 문제인 것 같습니다. #215 PR 이후로 발생한 문제로 보입니다.

**Comment by minyoy** [comment]
PR #266에서 수정하였습니다!
